package telemetry

// Per-invocation cost/usage metrics introduced by issue #1253 (1b).
//
// These instruments are aggregates: tag set is {agent_name, model,
// provider} only. Per-bead and per-prompt-SHA dimensions live in the
// WorkerOperation event log (#1252, 1a) — keeping them out of metrics
// bounds cardinality.
//
// Emission coverage: recorded for the transcript-backed provider families
// (claude, codex) driven through worker.SessionHandle prompt operations.
// Runtime-only sessions (worker.RuntimeHandle) are permanently out of scope
// (ga-tkvb31).

import (
	"context"
	"sync"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// invocationInstruments holds the lazy-initialized 1b instruments.
type invocationInstruments struct {
	tokensInput         metric.Int64Counter
	tokensOutput        metric.Int64Counter
	tokensCacheRead     metric.Int64Counter
	tokensCacheCreation metric.Int64Counter
	invocationLatencyMs metric.Float64Histogram
	invocationCostUSD   metric.Float64Counter
}

var (
	invInstOnce sync.Once
	invInst     invocationInstruments
)

// initInvocationInstruments registers the 1b instruments. Called lazily
// from the Record* helpers so tests using the otel test exporter pick up
// the production registrations without needing init order changes.
func initInvocationInstruments() {
	invInstOnce.Do(func() {
		m := otel.GetMeterProvider().Meter(meterRecorderName)

		invInst.tokensInput, _ = m.Int64Counter("gc.agent.tokens.input",
			metric.WithDescription("Total non-cached input tokens consumed by agent invocations"),
			metric.WithUnit("tokens"),
		)
		invInst.tokensOutput, _ = m.Int64Counter("gc.agent.tokens.output",
			metric.WithDescription("Total output tokens generated by agent invocations"),
			metric.WithUnit("tokens"),
		)
		invInst.tokensCacheRead, _ = m.Int64Counter("gc.agent.tokens.cache_read",
			metric.WithDescription("Total cached input tokens read by agent invocations"),
			metric.WithUnit("tokens"),
		)
		invInst.tokensCacheCreation, _ = m.Int64Counter("gc.agent.tokens.cache_creation",
			metric.WithDescription("Total tokens written into the prompt cache by agent invocations"),
			metric.WithUnit("tokens"),
		)
		invInst.invocationLatencyMs, _ = m.Float64Histogram("gc.agent.invocation.latency_ms",
			metric.WithDescription("LLM invocation wall-clock latency in milliseconds"),
			metric.WithUnit("ms"),
		)
		invInst.invocationCostUSD, _ = m.Float64Counter("gc.agent.invocation.cost_usd",
			metric.WithDescription("Estimated invocation cost in USD (decision-support, not invoice-grade)"),
			metric.WithUnit("USD"),
		)
	})
}

// InvocationLabels carries the {agent_name, model, provider} attribute
// set used by every 1b instrument. Bead-level dimensions (bead_id,
// prompt_sha) are deliberately excluded to keep cardinality bounded; they
// belong on the per-invocation event log instead.
type InvocationLabels struct {
	AgentName string
	Model     string
	Provider  string
}

func (l InvocationLabels) toOTel() []attribute.KeyValue {
	return []attribute.KeyValue{
		attribute.String("agent_name", l.AgentName),
		attribute.String("model", l.Model),
		attribute.String("provider", l.Provider),
	}
}

// RecordInvocationTokens emits the four token counters in a single call.
// Each token field is recorded only when > 0 to keep series sparse.
//
// Counters add cumulative volumes; aggregates over time windows answer
// "how many tokens did this (agent, model) pair burn in the last hour?".
func RecordInvocationTokens(ctx context.Context, labels InvocationLabels, prompt, completion, cacheRead, cacheCreation int64) {
	initInvocationInstruments()
	attrs := labels.toOTel()
	if prompt > 0 {
		invInst.tokensInput.Add(ctx, prompt, metric.WithAttributes(attrs...))
	}
	if completion > 0 {
		invInst.tokensOutput.Add(ctx, completion, metric.WithAttributes(attrs...))
	}
	if cacheRead > 0 {
		invInst.tokensCacheRead.Add(ctx, cacheRead, metric.WithAttributes(attrs...))
	}
	if cacheCreation > 0 {
		invInst.tokensCacheCreation.Add(ctx, cacheCreation, metric.WithAttributes(attrs...))
	}
}

// RecordInvocationLatency records the wall-clock latency of an LLM
// invocation. Use only for measured invocation latency — not for the
// duration of wrapper operations (those have their own histograms).
func RecordInvocationLatency(ctx context.Context, labels InvocationLabels, latencyMs float64) {
	initInvocationInstruments()
	if latencyMs <= 0 {
		return
	}
	invInst.invocationLatencyMs.Record(ctx, latencyMs, metric.WithAttributes(labels.toOTel()...))
}

// RecordInvocationCostEstimate records an estimated invocation cost.
// The recorder treats this as a counter — sum across a time window for
// "spend over the last 24 hours by (agent_name, model)".
//
// The estimate is computed by callers (typically using internal/pricing).
// Callers must label the surfaced number as an estimate everywhere it
// appears in user-facing output.
func RecordInvocationCostEstimate(ctx context.Context, labels InvocationLabels, costUSD float64) {
	initInvocationInstruments()
	if costUSD <= 0 {
		return
	}
	invInst.invocationCostUSD.Add(ctx, costUSD, metric.WithAttributes(labels.toOTel()...))
}
