//go:build ignore

// add-testenv-import normalizes internal/testenv wiring across the repo. It
// writes a canonical untagged testenv_import_test.go into every real test
// directory, removes stale generated files from directories that no longer
// contain tests, and scrubs legacy direct imports from non-canonical test
// files. Idempotent.
//
// Usage: go run scripts/add-testenv-import.go
//
// See PR #746 for context — this script wires every test binary into the
// GC_* env scrub via a dedicated file that is always present in the default
// test build for that directory.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	importPath = "github.com/gastownhall/gascity/internal/testenv"
	importFile = "testenv_import_test.go"
)

func main() {
	root, err := repoRoot()
	check(err)

	type dirInfo struct {
		packages      map[string]bool
		testFiles     []string
		canonicalFile string
	}
	dirInfos := map[string]*dirInfo{}

	// pkg/ is the public, OSS-consumable tree: its tests must NOT blank-import
	// internal/testenv, or an external module importing the package (cross-module
	// conformance replay) cannot compile them. Keep pkg/ packages testenv-free.
	skipDirs := map[string]bool{"vendor": true, "node_modules": true, ".git": true, "pkg": true}

	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if skipDirs[d.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, "_test.go") {
			return nil
		}
		rel, _ := filepath.Rel(root, filepath.Dir(path))
		if rel == "internal/testenv" {
			return nil
		}
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, parser.PackageClauseOnly)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		info := dirInfos[rel]
		if info == nil {
			info = &dirInfo{packages: map[string]bool{}}
			dirInfos[rel] = info
		}
		if filepath.Base(path) == importFile {
			info.canonicalFile = path
			return nil
		}
		info.packages[f.Name.Name] = true
		info.testFiles = append(info.testFiles, path)
		return nil
	})
	check(err)

	dirs := make([]string, 0, len(dirInfos))
	for d := range dirInfos {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)

	written := 0
	removed := 0
	scrubbed := 0
	unchanged := 0
	for _, dir := range dirs {
		info := dirInfos[dir]
		if len(info.testFiles) == 0 {
			if info.canonicalFile != "" {
				check(os.Remove(info.canonicalFile))
				fmt.Printf("removed stale: %s\n", info.canonicalFile)
				removed++
			}
			continue
		}
		target := filepath.Join(root, dir, importFile)
		content, err := renderImportFile(preferredPackage(info.packages))
		check(err)

		existing, err := os.ReadFile(target)
		switch {
		case err == nil:
			if !bytes.Equal(existing, content) {
				check(os.WriteFile(target, content, 0o644))
				fmt.Printf("wrote: %s\n", target)
				written++
			}
		case os.IsNotExist(err):
			check(os.WriteFile(target, content, 0o644))
			fmt.Printf("wrote: %s\n", target)
			written++
		default:
			check(err)
		}

		dirChanged := false
		for _, path := range info.testFiles {
			changed, err := scrubLegacyImport(path)
			check(err)
			if changed {
				fmt.Printf("scrubbed legacy import: %s\n", path)
				scrubbed++
				dirChanged = true
			}
		}
		if !dirChanged && err == nil && bytes.Equal(existing, content) {
			unchanged++
		}
	}
	fmt.Printf(
		"\n%d file(s) written, %d stale file(s) removed, %d legacy import(s) scrubbed, %d directory already up-to-date.\n",
		written,
		removed,
		scrubbed,
		unchanged,
	)
}

func preferredPackage(packages map[string]bool) string {
	names := make([]string, 0, len(packages))
	for pkg := range packages {
		names = append(names, pkg)
	}
	sort.Strings(names)
	for _, pkg := range names {
		if !strings.HasSuffix(pkg, "_test") {
			return pkg
		}
	}
	return names[0]
}

func renderImportFile(pkg string) ([]byte, error) {
	src := fmt.Sprintf(`// Code generated by go run scripts/add-testenv-import.go; DO NOT EDIT.

package %s

import _ %q
`, pkg, importPath)
	return format.Source([]byte(src))
}

func scrubLegacyImport(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, data, parser.ParseComments)
	if err != nil {
		return false, err
	}

	changed := false
	decls := make([]ast.Decl, 0, len(file.Decls))
	imports := make([]*ast.ImportSpec, 0, len(file.Imports))
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.IMPORT {
			decls = append(decls, decl)
			continue
		}
		specs := make([]ast.Spec, 0, len(gen.Specs))
		for _, spec := range gen.Specs {
			imp := spec.(*ast.ImportSpec)
			if strings.Trim(imp.Path.Value, `"`) == importPath {
				changed = true
				continue
			}
			specs = append(specs, spec)
			imports = append(imports, imp)
		}
		if len(specs) == 0 {
			continue
		}
		if len(specs) != len(gen.Specs) {
			gen.Specs = specs
		}
		decls = append(decls, gen)
	}
	if !changed {
		return false, nil
	}
	file.Decls = decls
	file.Imports = imports

	out, err := formatNode(fset, file)
	if err != nil {
		return false, err
	}
	if bytes.Equal(out, data) {
		return false, nil
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

func formatNode(fset *token.FileSet, file *ast.File) ([]byte, error) {
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, file); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from cwd")
		}
		dir = parent
	}
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
