package config

import (
	"crypto/sha256"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/gastownhall/gascity/internal/citylayout"
	"github.com/gastownhall/gascity/internal/git"
)

// packCacheDir is the subdirectory under .gc/cache/ where remote packs are cached.
const packCacheDir = citylayout.CachePacksRoot

// PackLock represents the lockfile state for reproducible builds.
type PackLock struct {
	Packs map[string]LockedPack `toml:"packs"`
}

// LockedPack records the exact state of a cached pack.
type LockedPack struct {
	Source string `toml:"source"`
	Ref    string `toml:"ref"`
	Commit string `toml:"commit"`
	Hash   string `toml:"hash"`
}

// FetchPacks ensures all remote packs are cached locally.
// Clones missing repos and updates existing ones to match the declared ref.
func FetchPacks(packs map[string]PackSource, cityRoot string) error {
	cacheRoot := filepath.Join(cityRoot, packCacheDir)
	if err := os.MkdirAll(cacheRoot, 0o755); err != nil {
		return fmt.Errorf("creating pack cache dir: %w", err)
	}

	for name, src := range packs {
		cacheDir := filepath.Join(cacheRoot, name)
		if _, err := os.Stat(filepath.Join(cacheDir, ".git")); err != nil {
			// Not yet cloned.
			if err := clonePack(src.Source, cacheDir, src.Ref); err != nil {
				return fmt.Errorf("pack %q: %w", name, err)
			}
		} else {
			// Already cloned — update to declared ref.
			if err := updatePack(cacheDir, src.Ref); err != nil {
				return fmt.Errorf("pack %q: %w", name, err)
			}
		}
	}
	return nil
}

// clonePack clones a git repo and checks out the specified ref.
func clonePack(source, cacheDir, ref string) error {
	args := []string{"clone", "--quiet"}
	if ref != "" {
		args = append(args, "--branch", ref)
	}
	args = append(args, "--depth", "1", source, cacheDir)

	if _, err := runGit("", args...); err != nil {
		return fmt.Errorf("cloning %s: %w", source, err)
	}
	return nil
}

// updatePack fetches and checks out the specified ref.
// The cache is a read-only mirror, so any local modifications are
// discarded before checkout to avoid "local changes would be
// overwritten" errors.
func updatePack(cacheDir, ref string) error {
	if _, err := runGit(cacheDir, "fetch", "--quiet", "origin"); err != nil {
		return fmt.Errorf("fetching: %w", err)
	}
	// Discard any local modifications in the cache working tree.
	_, _ = runGit(cacheDir, "checkout", "--force", ".")
	_, _ = runGit(cacheDir, "clean", "-fd")

	if ref == "" {
		if _, err := runGit(cacheDir, "checkout", "origin/HEAD"); err != nil {
			return fmt.Errorf("checking out origin/HEAD: %w", err)
		}
		return nil
	}
	// Try origin/<ref> first — for branches, this gets the latest remote state.
	// Fall back to <ref> for tags and commit SHAs.
	if _, err := runGit(cacheDir, "checkout", "origin/"+ref); err != nil {
		if _, err2 := runGit(cacheDir, "checkout", ref); err2 != nil {
			return fmt.Errorf("checking out %q: %w", ref, err2)
		}
	}
	return nil
}

// PackCachePath returns the cache directory for a named pack.
func PackCachePath(cityRoot, name string, src PackSource) string {
	dir := filepath.Join(cityRoot, packCacheDir, name)
	if src.Path != "" {
		dir = filepath.Join(dir, src.Path)
	}
	return dir
}

// ReadLock reads pack.lock from the city root.
// Returns an empty lock (not error) if the file doesn't exist.
func ReadLock(cityRoot string) (*PackLock, error) {
	path := filepath.Join(cityRoot, "pack.lock")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &PackLock{Packs: make(map[string]LockedPack)}, nil
		}
		return nil, fmt.Errorf("reading pack.lock: %w", err)
	}
	var lock PackLock
	if _, err := toml.Decode(string(data), &lock); err != nil {
		return nil, fmt.Errorf("parsing pack.lock: %w", err)
	}
	if lock.Packs == nil {
		lock.Packs = make(map[string]LockedPack)
	}
	return &lock, nil
}

// WriteLock writes pack.lock to the city root atomically.
func WriteLock(cityRoot string, lock *PackLock) error {
	path := filepath.Join(cityRoot, "pack.lock")
	tmp := path + ".tmp"

	f, err := os.Create(tmp)
	if err != nil {
		return fmt.Errorf("creating pack.lock: %w", err)
	}

	fmt.Fprintln(f, "# Auto-generated by gc pack fetch. Commit for reproducibility.") //nolint:errcheck
	fmt.Fprintln(f)                                                                   //nolint:errcheck

	enc := toml.NewEncoder(f)
	enc.Indent = ""
	if err := enc.Encode(lock); err != nil {
		f.Close()      //nolint:errcheck
		os.Remove(tmp) //nolint:errcheck // best-effort cleanup
		return fmt.Errorf("encoding pack.lock: %w", err)
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp) //nolint:errcheck // best-effort cleanup
		return fmt.Errorf("closing pack.lock: %w", err)
	}
	return os.Rename(tmp, path)
}

// LockFromCache builds lock state from current cache contents.
func LockFromCache(packs map[string]PackSource, cityRoot string) (*PackLock, error) {
	lock := &PackLock{Packs: make(map[string]LockedPack)}
	cacheRoot := filepath.Join(cityRoot, packCacheDir)

	for name, src := range packs {
		cacheDir := filepath.Join(cacheRoot, name)
		lt := LockedPack{
			Source: src.Source,
			Ref:    src.Ref,
		}

		// Get current commit.
		out, err := runGit(cacheDir, "rev-parse", "HEAD")
		if err == nil {
			lt.Commit = strings.TrimSpace(out)
		}

		// Compute content hash.
		topoDir := cacheDir
		if src.Path != "" {
			topoDir = filepath.Join(cacheDir, src.Path)
		}
		lt.Hash = "sha256:" + packDirHash(topoDir)

		lock.Packs[name] = lt
	}
	return lock, nil
}

// packDirHash computes a SHA-256 hash of all files in a directory (recursive).
func packDirHash(dir string) string {
	var paths []string
	filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error { //nolint:errcheck
		if err != nil {
			return nil
		}
		// Skip .git directories entirely.
		if d.IsDir() && d.Name() == ".git" {
			return filepath.SkipDir
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return nil
		}
		paths = append(paths, rel)
		return nil
	})
	sort.Strings(paths)

	h := sha256.New()
	for _, rel := range paths {
		data, err := os.ReadFile(filepath.Join(dir, rel))
		if err != nil {
			continue
		}
		h.Write([]byte(rel)) //nolint:errcheck
		h.Write([]byte{0})   //nolint:errcheck
		h.Write(data)        //nolint:errcheck
		h.Write([]byte{0})   //nolint:errcheck
	}
	return fmt.Sprintf("%x", h.Sum(nil))
}

// runGit executes a git command with a sanitized environment, so leaked GIT_*
// variables from a parent repository or a pre-commit hook cannot redirect it
// away from dir. If dir is non-empty, the command runs in that directory.
func runGit(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	if dir != "" {
		cmd.Dir = dir
	}
	cmd.Env = git.SanitizedEnv()
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("git %s: %s: %w", strings.Join(args, " "), strings.TrimSpace(string(out)), err)
	}
	return string(out), nil
}
